config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :categories
  resources :articles
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
    def to_s
    "#{name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]


  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @categories = Category.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    if user_signed_in?
    @article = Article.new
    end
  end

  # GET /articles/1/edit
  def edit
  end


  # POST /articles
  # POST /articles.json
  def create
    if user_signed_in?
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    end

  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if user_signed_in?
       @article.destroy
       respond_to do |format|
       format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
       format.json { head :no_content }
    end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :excerpt, :text, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.articles
  end

  # GET /categories/new
  def new
    if user_signed_in?
    @category = Category.new
    end
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    if user_signed_in?
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name,:color_from,:color_to)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <form class="form-signin">
  <label class="sr-only">Titre</label>
  <%= form.text_field :name, id: :article_name, :placeholder => "Titre de l'article" %><br>
  <div class="field">
  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <label class="sr-only">Chapo</label>
  <%= form.text_area :excerpt, id: :article_excerpt, :placeholder => "Résumé" %><br>
  <label class="sr-only">Texte</label>
  <%= form.text_area :text, :class => "tinymce", :placeholder => "Texte"%>
  <%= form.submit %>
  </form>
<% end %>
<%= tinymce %>

app/views/articles/_list.html.erb
<div class="card-columns">
  <% @articles.each do |article| %>
    <%= link_to article do %>
      <div class="card card-path">
        <div class="card-body">
          <h5 class="card-title"><%= article.name %></h5>
          <p class="card-text"><%= article.excerpt %></p>
        </div>
        <%= link_to article do %>
          <p class="lecture category" style ="background: linear-gradient(to right, <%= article.category.color_from%>,<%= article.category.color_to%>)"%>Lire ⇾</p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/edit.html.erb
    <div class="card article">
      <p class="etudes titre">Modifier un article</p>
      <div class="card-body">
        <%= render 'form', article: @article %>
      </div>
    </div>

app/views/articles/index.html.erb
<%= render 'list' %>

app/views/articles/new.html.erb
    <div class="card article">
      <p class="travail titre">Nouvel article</p>
      <div class="card-body">
        <%= render 'form', article: @article %>
      </div>
    </div>

app/views/articles/show.html.erb
<div class="card article">
  <p class="titre" style="background : linear-gradient(to right, <%= @article.category.color_from%>, <%= @article.category.color_to%>);"><%=@article.category %></p>
  <%= link_to articles_path do %>
    <div class="cross"></div>
  <% end %>
  <div class="card-body body-article">
    <h5 class="card-title-article"><%= @article.name %></h5>
    <p class="card-text-excerpt"><%= @article.excerpt %></p>
    <p class="card-text-article"><%= @article.text.html_safe %></p>
  </div>
  <% unless user_signed_in?%>
    <center>
      <div class="edit">
        <%= link_to 'Retour', articles_path, :class => "btn btn-outline-dark", :style=>'margin:50px;' %>
      </div>
    </center>
  <% end %>
  <% if user_signed_in?%>
    <div class="edit">
      <%= link_to 'Modifier', edit_article_path(@article), :class => "btn btn-secondary", :style=>'color:#FFFFFF;margin-bottom:15px;' %>
      <%= link_to 'Supprimer', @article, method: :delete, data: { confirm: 'Etes-vous sur ?' }, :class => "btn btn-danger", :style=>'color:#FFFFFF;margin-bottom:15px;' %>
   </div>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>
    <div class="field">
    <%= form.label :color_from %>
    <%= form.text_field :color_from, id: :category_color_from %>
  </div>
   <div class="field">
    <%= form.label :color_to %>
    <%= form.text_field :color_to, id: :category_color_to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= render 'articles/list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Krizalid</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 topbar">
      <%= link_to root_path do %>
        <%= content_tag :div, "", class: "mr-md-auto logo" %>
      <% end %>
      <nav class="my-2 my-md-0">
        <% Category.all.each do |category| %>
          <%= link_to category,
                      category,
                      class: 'btn btn-outline-primary top-btt category',
                      style: "background: linear-gradient(to right, #{category.color_from}, #{category.color_to}); transition: 0.3s" %>
        <% end %>
      </nav>
      <% if user_signed_in? %>
        <%= link_to new_article_path do %>
          <%= content_tag :div, "Nouvel article", :class => "btn btn-outline-warning" %>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <%= content_tag :div, "Déconnexion", :class => "btn btn-outline-danger" %>
        <% end %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  </body>
</html>